/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsYamlWorkflowsRouteImport } from './routes/docs.yaml-workflows'
import { Route as DocsUseCasesRouteImport } from './routes/docs.use-cases'
import { Route as DocsTypescriptRouteImport } from './routes/docs.typescript'
import { Route as DocsPythonRouteImport } from './routes/docs.python'
import { Route as DocsCoreConceptsRouteImport } from './routes/docs.core-concepts'
import { Route as DocsContributingRouteImport } from './routes/docs.contributing'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as DocsChangelogRouteImport } from './routes/docs.changelog'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsYamlWorkflowsRoute = DocsYamlWorkflowsRouteImport.update({
  id: '/yaml-workflows',
  path: '/yaml-workflows',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUseCasesRoute = DocsUseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTypescriptRoute = DocsTypescriptRouteImport.update({
  id: '/typescript',
  path: '/typescript',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonRoute = DocsPythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCoreConceptsRoute = DocsCoreConceptsRouteImport.update({
  id: '/core-concepts',
  path: '/core-concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsContributingRoute = DocsContributingRouteImport.update({
  id: '/contributing',
  path: '/contributing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChangelogRoute = DocsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/contributing': typeof DocsContributingRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/python': typeof DocsPythonRoute
  '/docs/typescript': typeof DocsTypescriptRoute
  '/docs/use-cases': typeof DocsUseCasesRoute
  '/docs/yaml-workflows': typeof DocsYamlWorkflowsRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/contributing': typeof DocsContributingRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/python': typeof DocsPythonRoute
  '/docs/typescript': typeof DocsTypescriptRoute
  '/docs/use-cases': typeof DocsUseCasesRoute
  '/docs/yaml-workflows': typeof DocsYamlWorkflowsRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/contributing': typeof DocsContributingRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/python': typeof DocsPythonRoute
  '/docs/typescript': typeof DocsTypescriptRoute
  '/docs/use-cases': typeof DocsUseCasesRoute
  '/docs/yaml-workflows': typeof DocsYamlWorkflowsRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/architecture'
    | '/docs/changelog'
    | '/docs/cli'
    | '/docs/contributing'
    | '/docs/core-concepts'
    | '/docs/python'
    | '/docs/typescript'
    | '/docs/use-cases'
    | '/docs/yaml-workflows'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/docs/architecture'
    | '/docs/changelog'
    | '/docs/cli'
    | '/docs/contributing'
    | '/docs/core-concepts'
    | '/docs/python'
    | '/docs/typescript'
    | '/docs/use-cases'
    | '/docs/yaml-workflows'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/architecture'
    | '/docs/changelog'
    | '/docs/cli'
    | '/docs/contributing'
    | '/docs/core-concepts'
    | '/docs/python'
    | '/docs/typescript'
    | '/docs/use-cases'
    | '/docs/yaml-workflows'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/yaml-workflows': {
      id: '/docs/yaml-workflows'
      path: '/yaml-workflows'
      fullPath: '/docs/yaml-workflows'
      preLoaderRoute: typeof DocsYamlWorkflowsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/use-cases': {
      id: '/docs/use-cases'
      path: '/use-cases'
      fullPath: '/docs/use-cases'
      preLoaderRoute: typeof DocsUseCasesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/typescript': {
      id: '/docs/typescript'
      path: '/typescript'
      fullPath: '/docs/typescript'
      preLoaderRoute: typeof DocsTypescriptRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python': {
      id: '/docs/python'
      path: '/python'
      fullPath: '/docs/python'
      preLoaderRoute: typeof DocsPythonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/core-concepts': {
      id: '/docs/core-concepts'
      path: '/core-concepts'
      fullPath: '/docs/core-concepts'
      preLoaderRoute: typeof DocsCoreConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/contributing': {
      id: '/docs/contributing'
      path: '/contributing'
      fullPath: '/docs/contributing'
      preLoaderRoute: typeof DocsContributingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/changelog': {
      id: '/docs/changelog'
      path: '/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof DocsChangelogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsChangelogRoute: typeof DocsChangelogRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsContributingRoute: typeof DocsContributingRoute
  DocsCoreConceptsRoute: typeof DocsCoreConceptsRoute
  DocsPythonRoute: typeof DocsPythonRoute
  DocsTypescriptRoute: typeof DocsTypescriptRoute
  DocsUseCasesRoute: typeof DocsUseCasesRoute
  DocsYamlWorkflowsRoute: typeof DocsYamlWorkflowsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsChangelogRoute: DocsChangelogRoute,
  DocsCliRoute: DocsCliRoute,
  DocsContributingRoute: DocsContributingRoute,
  DocsCoreConceptsRoute: DocsCoreConceptsRoute,
  DocsPythonRoute: DocsPythonRoute,
  DocsTypescriptRoute: DocsTypescriptRoute,
  DocsUseCasesRoute: DocsUseCasesRoute,
  DocsYamlWorkflowsRoute: DocsYamlWorkflowsRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
